centos: fix lxml & xmlsec library version mismatch
when importing the saml in the dashboard, it fails with
```
xmlsec.InternalError: (-1, 'lxml & xmlsec libxml2 library version mismatch')
```
which prevents dashboard from starting. Trying to fix it with a pinned
version of xmlsec (because the newer one is failing to install in
centos9 because of the known binary wheels issue)

Signed-off-by: Nizamudeen A <nia@redhat.com>